import type { Skill } from "./types.js";

export const pythonSkill: Skill = {
  id: "python",
  label: "Python",
  searchTag: "Python class module function",
  searchContextPrefix:
    "Python codebase: focus on module structure, class definitions, data models, and service functions.",
  cardPromptHints:
    "This is a Python application. Emphasize: module imports, class inheritance, type hints, data models (Pydantic/dataclass), and common patterns like context managers and decorators.",
  docTypeWeights: {
    about: 0.9,
    architecture: 1.0,
    rules: 0.9,
    code_style: 1.0,
    specialist: 1.2,
  },
  classifierOverrides: [
    { pattern: /test_.*\.py$/, role: "test" },
    { pattern: /.*_test\.py$/, role: "test" },
    { pattern: /conftest\.py$/, role: "config" },
    { pattern: /__init__\.py$/, role: "entry_point" },
    { pattern: /\/migrations?\//, role: "config" },
  ],
  bestPractices: {
    architecture: [
      "Use type hints throughout — they are not optional in professional Python",
      "Separate domain logic from I/O; keep functions pure where possible",
      "Use dataclasses or Pydantic models for structured data transfer objects",
      "Manage dependencies with pyproject.toml + uv or pip-tools; pin versions in requirements.txt",
      "Use virtual environments; never install packages to the system Python",
    ],
    codeStyle: [
      "Follow PEP 8 for formatting; enforce with ruff or black",
      "Use f-strings for string interpolation (not % or .format())",
      "Prefer context managers (with statement) for resource management",
      "Use generators over lists for large sequences to avoid loading everything into memory",
      "Keep functions short and single-purpose; 20-line limit is a reasonable guide",
    ],
    testing: [
      "Use pytest; avoid unittest unless maintaining legacy code",
      "Use fixtures for setup; parametrize for data-driven tests",
      "Use pytest-mock for mocking; patch at the point of use not the point of definition",
      "Aim for 80%+ coverage on business logic; exclude I/O-heavy integration code from unit tests",
      "Name test files test_*.py or *_test.py; name test functions test_<behavior>",
    ],
    performance: [
      "Use list/dict/set comprehensions over explicit for-loops for simple transformations",
      "Profile with cProfile or py-spy before optimizing",
      "Use asyncio for I/O-bound concurrency; use multiprocessing for CPU-bound work",
      "Cache expensive computations with functools.lru_cache or functools.cache",
      "Use slots in dataclasses or classes with many instances to reduce memory overhead",
    ],
    security: [
      "Never use eval() or exec() with user-supplied input",
      "Validate and sanitize all external inputs with Pydantic or cerberus",
      "Use parameterized queries (never format SQL strings with user data)",
      "Store secrets in environment variables; use python-dotenv or similar for local dev",
      "Use secrets module for cryptographic tokens, not random",
    ],
    antiPatterns: [
      "Mutable default arguments (def foo(x=[]) — the list is shared across all calls)",
      "Bare except clauses that swallow all exceptions",
      "Using type: ignore comments as a substitute for fixing type errors",
      "Circular imports between modules",
      "Global state that makes functions non-deterministic and hard to test",
    ],
  },
  verificationHints: {
    confirmThreshold: 0.75,
    knownExceptions: [
      "Script files with if __name__ == '__main__': blocks",
      "Migration files generated by Alembic or Django",
      "Jupyter notebooks (*.ipynb)",
      "Configuration files (conftest.py, setup.py)",
    ],
  },
};

export default pythonSkill;
